// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic"

export const components = {
  clients_say: dynamic(() => import("./ClientsSay")),
  hero: dynamic(() => import("./Hero")),
}
